version: '3'
services:
  server:
    build:
      context: ./Back/
    ports:
      - "8080:8000"
    volumes:
      - server-data:/var/www/html
    command: /start.sh

  client_web:
    build:
      context: ./Front/WEB/
    ports:
      - "8081:8080"
    volumes:
      - shared-data:/app/shared
    command: npm run dev
    networks:
      - my-network


  client_mobile:
    build:
      context: ./Front/MOBILE/MOBILE/
    volumes:
      - shared-data:/shared
    command: ["tail", "-f", "/dev/null"] # Cette commande maintient le conteneur en cours d'exécution
    networks:
      - my-network

volumes:
  server-data:
  shared-data:

networks:
  my-network:
    driver: bridge
