version: '3'
services:
  server:
    build:
      context: ./Back/ # Chemin vers le répertoire de votre back-end
    ports:
      - "8000:8000"
    volumes:
      - server-data:/var/www/html
    command: /start.sh
    networks:
      - your-network

  client_mobile:
    build:
      context: ./Front/MOBILE/MOBILE/ # Chemin vers le répertoire de votre application mobile
    volumes:
      - shared-data:/shared
    command: /MOBILE # Remplacez par le nom de l'exécutable mobile
    networks:
      - your-network

  client_web:
    build:
      context: ./Front/WEB/ # Chemin vers le répertoire de votre application web
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/app/shared
    command: npm run dev
    networks:
      - your-network

networks:
  your-network:
    driver: bridge

volumes:
  server-data:
  shared-data:
