name: AREA

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-BDX-5-1-area-max.peixoto.git"

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Check SSH key
        run: |
          ls -l ~/.ssh/
          ls -l ~/.ssh/id_rsa
          # Ajoutez des commandes pour vérifier les permissions si nécessaire

      - name: Push to Epitech repository
        run:  |
          git remote add mirror $MIRROR_URL
          git fetch mirror

          # Get the current branch name
          BRANCH_NAME=$(git symbolic-ref --short HEAD)

          # Check if the branch exists on the mirror repository
          if git rev-parse --verify "mirror/$BRANCH_NAME" >/dev/null 2>&1; then
            # If the branch exists, push changes to it
            git push mirror $BRANCH_NAME
          else
            # If the branch doesn't exist, create it on the mirror repository
            git push mirror $BRANCH_NAME:$BRANCH_NAME
          fi
