name: AREA

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-BDX-5-1-area-max.peixoto.git"

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Another Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
